name: Testing

on:
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Xdebug actions
        uses: mileschou/docker-xdebug@master
        with:
          args: php -v && php -m
